###
PUT http://localhost:4000/lists/1
Content-Type: application/json

{
  "listName": "test test test",
  "createdAt": 1625816641626,
  "color": "yellow",
  "description": "test description"
}

###
DELETE HTTP/1.1 http://localhost:4000/lists/6
Content-Type: application/json

{
  "listName": "test test test",
  "createdAt": 1625816641626,
  "color": "yellow",
  "description": "test description"
}

###
GET http://localhost:4000/lists

###
DELETE http://localhost:4000/lists/6
